# Server
server.name: kibana
server.host: "0.0.0.0"
server.port: 5601

# Elasticsearch
elasticsearch.hosts: [ "http://elasticsearch:9200" ]

# Security
xpack.security.enabled: True
xpack.security.encryptionKey: cVsoUTdKOWScqL+xAhcmJRPfraaBxl1234
xpack.encryptedSavedObjects.encryptionKey: "cVsoUTdKOWScqL+xAhcmJRPfraaBxl"

# Reporting
xpack.reporting.encryptionKey: "cVsoUTdKOWScqL+xAhcmJRPfraaBxl"
xpack.reporting.kibanaServer.hostname: "0.0.0.0"
xpack.reporting.capture.browser.chromium.disableSandbox: True

# Monitoring
xpack.monitoring.enabled: True
xpack.monitoring.cluster_alerts.email_notifications.email_address: "your-email@example.com"

# Logging
logging.root.level: info
logging.root.appenderRef.console: ref(console)

appender.console.type: console
appender.console.layout.type: pattern
appender.console.layout.pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

loggers:
- name: org.elasticsearch
  level: info
  appenderRef.console: ref(console)
- name: org.elasticsearch.client
  level: info
  appenderRef.console: ref(console)
- name: org.elasticsearch.deprecation
  level: warn
  appenderRef.console: ref(console)
- name: org.elasticsearch.plugins
  level: info
  appenderRef.console: ref(console)
- name: org.elasticsearch.transport
  level: warn
  appenderRef.console: ref(console)
- name: org.elasticsearch.http
  level: warn
  appenderRef.console: ref(console)
- name: org.elasticsearch.indices
  level: warn
  appenderRef.console: ref(console)
- name: org.elasticsearch.cluster
  level: warn
  appenderRef.console: ref(console)
- name: org.elasticsearch.node
  level: warn
  appenderRef.console: ref(console)
- name: org.elasticsearch.discovery
  level: warn
  appenderRef.console: ref(console)
- name: org.elasticsearch.gateway
  level: warn
  appenderRef.console: ref(console)
- name: org.elasticsearch.snapshots
  level: warn
  appenderRef.console: ref(console)
- name: org.elasticsearch.repositories
  level: warn
  appenderRef.console: ref(console)
- name: org.elasticsearch.action
  level: warn
  appenderRef.console: ref(console)
- name: org.elasticsearch.bootstrap
  level: warn
  appenderRef.console: ref(console)
- name: org.elasticsearch.index
  level: warn
  appenderRef.console: ref(console)
- name: org.elasticsearch.search
  level: warn
  appenderRef.console: ref(console)
