version: '3.8'

services:
  grafana:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_RENDERING_SERVER_URL=http://grafana-image-renderer:8085/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
    depends_on:
      - grafana-image-renderer
    restart: unless-stopped

  grafana-image-renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - "8085:8085"
    environment:
      - CHROME_BIN=/usr/bin/chromium
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    restart: unless-stopped

volumes:
  grafana-storage: 