services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - 9200:9200
    platform: linux/amd64

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.2
    volumes:
      - ./logstash/config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - 5044:5044/tcp
      - 514:514/udp
      - 514:514/tcp
    environment:
      LS_JAVA_OPTS: "-Xmx128m -Xms128m"
    platform: linux/amd64

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5601
      - XPACK_SECURITY_ENABLED=True
      - XPACK_SECURITY_ENCRYPTIONKEY=cVsoUTdKOWScqL+xAhcmJRPfraaBxl1234
    ports:
      - 5601:5601
    platform: linux/amd64

networks:
  default:
    name: elk_test
    external: True
