# Server
server.host: "0.0.0.0"
server.port: 5601

# Elasticsearch
elasticsearch.hosts: ["http://elasticsearch:9200"]

# Security
xpack.security.enabled: true
xpack.security.encryptionKey: "cVsoUTdKOWScqL+xAhcmJRPfraaBxl"
xpack.encryptedSavedObjects.encryptionKey: "cVsoUTdKOWScqL+xAhcmJRPfraaBxl"

# Reporting
xpack.reporting.encryptionKey: "cVsoUTdKOWScqL+xAhcmJRPfraaBxl"
xpack.reporting.kibanaServer.hostname: "0.0.0.0"
xpack.reporting.capture.browser.chromium.disableSandbox: true

# Monitoring
xpack.monitoring.enabled: true
xpack.monitoring.cluster_alerts.email_notifications.email_address: "your-email@example.com"

# Logging
logging.root.level: info
logging.root.appenderRefs: ["console"]
logging.appenders.console.type: console
logging.appenders.console.layout.type: json
